#!/bin/bash
# GitHub Push & Deployment Script
# Run this script after creating your GitHub repository

echo "=== Online Job Portal: GitHub & Deployment Setup ==="
echo ""
echo "Step 1: Create GitHub Repository"
echo "Visit: https://github.com/new"
echo "Repository name: online-job-portal"
echo "Description: Role-based job portal with React + Express"
echo "Visibility: Public"
echo "Do NOT initialize with README (we have one)"
echo ""
echo "After creating repo, copy the HTTPS URL and run:"
echo ""
echo "Step 2: Add Remote and Push Code"
echo "========================================"
echo ""

# Replace YOUR_USERNAME with actual GitHub username
GITHUB_USERNAME="YOUR_USERNAME"
REPO_NAME="online-job-portal"

echo "Run these commands in your project directory:"
echo ""
echo "git remote add origin https://github.com/${GITHUB_USERNAME}/${REPO_NAME}.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "========================================"
echo ""
echo "Step 3: Deploy Frontend on Vercel"
echo "1. Go to https://vercel.com"
echo "2. Sign in with GitHub"
echo "3. Import your online-job-portal repository"
echo "4. Leave settings as default (Vite will auto-detect)"
echo "5. Deploy"
echo ""
echo "You'll get a URL like: https://online-job-portal.vercel.app"
echo ""
echo "Step 4: Deploy Backend on Railway"
echo "1. Go to https://railway.app"
echo "2. Sign in with GitHub"
echo "3. Create New Project"
echo "4. Deploy from GitHub repo → select online-job-portal"
echo "5. Add MySQL database plugin"
echo "6. Set environment variables (see .env.production)"
echo "7. Deploy"
echo ""
echo "Step 5: Connect Frontend to Backend"
echo "In Vercel environment variables:"
echo "  VITE_API_BASE_URL=https://your-railway-url/api"
echo ""
echo "=== Setup Complete! ==="
